name: Run mymy on modified cdk files

on:
  pull_request:
    paths:
      - "airbyte-cdk/python/**"
jobs:
  run-mypy-on-modified-cdk-files:
    name: "Run mypy on modified cdk files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Get Python changed files
        id: changed-py-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            *.py
            **/*.py
      - name: Run if any of the listed files above is changed
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --ignore-missing-imports
